import { useState } from "react";
import { Sparkles, Download, Save, Copy, RefreshCw } from "lucide-react";

export function AIDocumentGenerator() {
  const [prompt, setPrompt] = useState("");
  const [generatedContent, setGeneratedContent] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);

  const quickPrompts = [
    "Generate a comprehensive course syllabus for Data Structures and Algorithms",
    "Create a lesson plan for Introduction to Programming with learning outcomes",
    "Design a rubric for evaluating student research papers",
    "Draft a midterm examination for Database Management Systems",
    "Write learning module content for Object-Oriented Programming",
  ];

  const handleGenerate = () => {
    if (!prompt.trim()) return;

    setIsGenerating(true);
    setTimeout(() => {
      setGeneratedContent(`# AI-Generated Academic Document

## Document Overview
Based on your prompt: "${prompt}"

### Section 1: Introduction
This section provides a comprehensive overview of the topic, outlining the key concepts and objectives that will be covered throughout the document.

### Section 2: Learning Outcomes
Upon completion, students will be able to:
- Demonstrate understanding of core concepts
- Apply theoretical knowledge to practical scenarios
- Analyze and evaluate complex problems
- Create solutions using appropriate methodologies

### Section 3: Content Structure
The document follows a structured approach designed to facilitate progressive learning and ensure comprehensive coverage of the subject matter.

### Section 4: Assessment and Evaluation
Multiple assessment methods will be employed to evaluate student understanding and progress, including formative and summative assessments.

### Section 5: Resources and References
A curated list of academic resources, textbooks, and supplementary materials to support learning and further exploration.

---
*Generated by CTU Knowledge System AI Assistant*`);
      setIsGenerating(false);
    }, 3000);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedContent);
    alert("Content copied to clipboard!");
  };

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl sm:text-2xl font-bold text-gray-900 flex items-center gap-2">
            <Sparkles className="h-6 w-6 text-[#DD7230]" />
            AI Document Generator
          </h1>
          <p className="text-xs sm:text-sm text-gray-500 mt-0.5">Generate institutional academic documents and governance templates using AI assistance</p>
        </div>
      </div>

      {/* AI Prompt Section */}
      <div className="bg-white rounded-2xl border border-gray-200 p-5 sm:p-6 shadow-2xs">
        <h2 className="text-sm font-bold text-gray-900 mb-3 flex items-center gap-2">
          Describe Your Document Requirements
        </h2>
        <div className="space-y-4">
          <div>
            <label className="block text-xs font-semibold text-gray-700 mb-1.5">Prompt & Context</label>
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              rows={5}
              className="w-full p-4 bg-gray-50/60 border border-gray-200 rounded-xl text-xs text-gray-900 focus:outline-none focus:ring-2 focus:ring-[#DD7230] focus:bg-white transition-all placeholder-gray-400"
              placeholder="Describe the document you want to generate (e.g. syllabus, lesson plan, exam rubric, or departmental memo with objectives and grading criteria)..."
            />
          </div>

          <button
            onClick={handleGenerate}
            disabled={isGenerating || !prompt.trim()}
            className="w-full flex items-center justify-center gap-2 px-5 py-2.5 bg-[#DD7230] text-white rounded-xl hover:bg-[#DD7230] transition-colors text-xs font-semibold shadow-2xs cursor-pointer active:scale-98 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isGenerating ? (
              <>
                <RefreshCw className="h-4 w-4 animate-spin" />
                Generating Document with AI...
              </>
            ) : (
              <>
                <Sparkles className="h-4 w-4" />
                Generate Document
              </>
            )}
          </button>
        </div>
      </div>

      {/* Quick Prompts */}
      <div className="bg-white rounded-2xl border border-gray-200 p-5 sm:p-6 shadow-2xs">
        <h2 className="text-sm font-bold text-gray-900 mb-3">Quick Presets</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
          {quickPrompts.map((quickPrompt, index) => (
            <button
              key={index}
              onClick={() => setPrompt(quickPrompt)}
              className="text-left p-3.5 bg-gray-50/60 rounded-xl hover:bg-orange-50/50 hover:border-[#DD7230]/40 border border-gray-200 transition-all cursor-pointer group"
            >
              <p className="text-gray-700 text-xs font-medium group-hover:text-gray-900 transition-colors">{quickPrompt}</p>
            </button>
          ))}
        </div>
      </div>

      {/* Generated Content */}
      {generatedContent && (
        <div className="bg-white rounded-2xl border border-gray-200 p-5 sm:p-6 shadow-2xs space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="text-sm font-bold text-gray-900">Generated Output</h2>
            <div className="flex gap-2">
              <button
                onClick={handleCopy}
                className="flex items-center gap-1.5 px-3.5 py-1.5 text-xs font-semibold text-gray-700 bg-white border border-gray-200 rounded-xl hover:bg-gray-50 transition-colors cursor-pointer"
              >
                <Copy className="h-3.5 w-3.5" />
                Copy
              </button>
              <button className="flex items-center gap-1.5 px-3.5 py-1.5 text-xs font-semibold bg-[#DD7230] text-white rounded-xl hover:bg-[#DD7230] transition-colors shadow-2xs cursor-pointer">
                <Download className="h-3.5 w-3.5" />
                Export
              </button>
            </div>
          </div>

          <div className="p-5 bg-gray-50/60 rounded-xl border border-gray-200">
            <pre className="whitespace-pre-wrap text-gray-800 font-sans text-xs leading-relaxed">
              {generatedContent}
            </pre>
          </div>

          <div className="p-3.5 bg-orange-50 border border-[#DD7230]/20 rounded-xl text-xs text-gray-700">
            <p>
              <strong className="text-gray-900">Note:</strong> This is AI-generated draft content. Please review and verify alignment with CTU institutional policies before official publication.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
